Repository Capstone-Clothing/CODINAVI, pull requests merged in 2024-06, with the labels that each got.

#15 디바이스 설정에 영향을 받지 않도록 텍스트 사이즈 고정
  app/src/main/res/layout/activity_admin.xml
  app/src/main/res/layout/activity_camera.xml
  app/src/main/res/layout/activity_codi.xml
  app/src/main/res/layout/activity_color.xml
  app/src/main/res/layout/activity_confirm.xml
  app/src/main/res/layout/activity_gender.xml
  app/src/main/res/layout/activity_guide.xml
  app/src/main/res/layout/activity_introduce_app_btn.xml
  app/src/main/res/layout/activity_introduce_appc_btn.xml
  app/src/main/res/layout/activity_introduce_camera_btn.xml
  app/src/main/res/layout/activity_introduce_weather_btn.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_otherlocation.xml
  app/src/main/res/layout/activity_othertime.xml
  app/src/main/res/layout/activity_search_otherlocation.xml
  app/src/main/res/layout/activity_search_othertime.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/activity_user.xml
  app/src/main/res/layout/activity_weather.xml
Labels: 🌟Frontend, 🎨UI

#17 화면 위치에 따른 버튼 및 뷰 위치 통일성 개선
  app/src/main/java/com/example/capstonecodinavi/Admin/AdminActivity.kt
  app/src/main/java/com/example/capstonecodinavi/Login/LoginActivity.kt
  app/src/main/java/com/example/capstonecodinavi/Weather/WeatherActivity.kt
  app/src/main/res/layout/activity_camera.xml
  app/src/main/res/layout/activity_codi.xml
  app/src/main/res/layout/activity_color.xml
  app/src/main/res/layout/activity_otherlocation.xml
  app/src/main/res/layout/activity_search_otherlocation.xml
  app/src/main/res/layout/activity_weather.xml
Labels: 🌟Frontend, 🎨UI

#23 상황별 페이지 생성
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/capstonecodinavi/Recommend/OccasionActivity.kt
  app/src/main/res/layout/activity_occasion.xml
Labels: 🌟Frontend, 🎨UI

#24 사용설명서 내용 추가 및 구성 변경
  app/src/main/res/layout/activity_introduce_app_btn.xml
  app/src/main/res/layout/activity_introduce_appc_btn.xml
  app/src/main/res/layout/activity_introduce_camera_btn.xml
  app/src/main/res/layout/activity_introduce_weather_btn.xml
Labels: 🌟Frontend, 🎨UI

#21 Feat/10 : 현재 날씨와 1시간 간격 날씨 정보의 데이터 연결 완료
  app/src/main/java/com/example/capstonecodinavi/Weather/SearchOthertime.kt
  app/src/main/java/com/example/capstonecodinavi/Weather/WeatherActivity.kt
  app/src/main/res/layout/activity_search_othertime.xml
Labels: 🔥Backend, 🌟Frontend, ✨Feat

#29 구글 로그인 기능 제거
  app/build.gradle.kts
  app/src/main/java/com/example/capstonecodinavi/Login/LoginActivity.kt
  app/src/main/java/com/example/capstonecodinavi/User/UserActivity.kt
  app/src/main/res/layout/activity_login.xml
Labels: ♻️Refactor

#31 성별 입력 및 변경 기능 구현
  app/src/main/res/layout/activity_first_gender_set.xml
  app/src/main/res/layout/activity_gender.xml
Labels: 🌟Frontend, 🎨UI

#36 상황별 코디 판별 UI 페이지 생성
  app/src/main/java/com/example/capstonecodinavi/Camera/CameraActivity.kt
  app/src/main/res/layout/activity_camera.xml
Labels: 🌟Frontend, 🎨UI

#45 기온별 옷차림 DB 추천아이템 멘트 수정
  app/src/main/java/com/example/capstonecodinavi/Weather/OthertimeActivity.kt
  app/src/main/java/com/example/capstonecodinavi/Weather/WeatherActivity.kt
Labels: 🌟Frontend, 🎨UI

#51 Othertime 액티비티 UI 수정
  app/src/main/java/com/example/capstonecodinavi/Weather/OthertimeActivity.kt
  app/src/main/res/layout/activity_otherlocation.xml
  app/src/main/res/layout/activity_othertime.xml
  app/src/main/res/layout/activity_weather.xml
Labels: 🌟Frontend, 🎨UI

#55 FixBug: OtherlocationActivity에서 일정 지역에서의 한줄평 안나오는 오류 고침 #53
  app/src/main/java/com/example/capstonecodinavi/Weather/OtherlocationActivity.kt
Labels: 🐛FixBug
