Repository Capstone-Clothing/CODINAVI, pull requests merged in 2024-08, with the labels that each got.

#61 feat: 상황별 키워드에 따른 코디 판별 기능(임시 데이터)
  app/src/main/java/com/example/capstonecodinavi/Recommend/OccasionActivity.kt
  app/src/main/java/com/example/capstonecodinavi/Recommend/SearchOccasionActivity.kt
  app/src/main/res/layout/activity_occasion.xml
Labels: 🌟Frontend, ✨Feat

#65 UI: 이전 추천 결과 확인하기
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/capstonecodinavi/User/RecommendResultActivity.kt
  app/src/main/java/com/example/capstonecodinavi/User/ResultListActivity.kt
  app/src/main/java/com/example/capstonecodinavi/User/UserActivity.kt
  app/src/main/res/drawable/rectangle_5.xml
  app/src/main/res/layout/activity_recommend_result.xml
  app/src/main/res/layout/activity_result_list.xml
  app/src/main/res/layout/activity_user.xml
Labels: 🌟Frontend, 🎨UI

#67 refactor: 상황별 키워드에 따른 코디 판별
  app/src/main/java/com/example/capstonecodinavi/Recommend/OccasionActivity.kt
Labels: ♻️Refactor
